version: '3.8'

services:
  web:
    build: .
    ports:
      - "51313:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=wsgi.py
      - DATABASE_URL=postgresql://bot_admin:wewffikp@db:5432/telegram_bot_db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=bot_admin
      - POSTGRES_PASSWORD=wewffikp
      - POSTGRES_DB=telegram_bot_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery_worker:
    build: .
    command: celery -A app.tasks.bot_tasks worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://bot_admin:wewffikp@db:5432/telegram_bot_db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis

  celery_beat:
    build: .
    command: celery -A app.tasks.bot_tasks beat --loglevel=info
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://bot_admin:wewffikp@db:5432/telegram_bot_db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis

  flower:
    build: .
    command: celery -A app.tasks.bot_tasks flower --port=5555
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - celery_worker
      - redis

volumes:
  postgres_data:
  redis_data: